# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/vs920/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/lge/vs920/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
    vendor/lge/vs920/proprietary/lib/libnv.so:obj/lib/libnv.so \
    # vendor/lge/vs920/proprietary/lib/libaudio.so:obj/lib/libaudio.so \
    vendor/lge/vs920/proprietary/lib/libv8.so:obj/lib/libv8.so

PRODUCT_COPY_FILES += \
    vendor/lge/vs920/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/lge/vs920/proprietary/lib/egl/libq3dtools_adreno200.so:system/lib/egl/libq3dtools_adreno200.so \
    vendor/lge/vs920/proprietary/lib/egl/libGLESv2_adreno200.so:system/lib/egl/libGLESv2_adreno200.so \
    vendor/lge/vs920/proprietary/lib/egl/libGLESv1_CM_adreno200.so:system/lib/egl/libGLESv1_CM_adreno200.so \
    vendor/lge/vs920/proprietary/lib/egl/libGLESv2S3D_adreno200.so:system/lib/egl/libGLESv2S3D_adreno200.so \
    vendor/lge/vs920/proprietary/lib/egl/libEGL_adreno200.so:system/lib/egl/libEGL_adreno200.so \
    vendor/lge/vs920/proprietary/lib/egl/eglsubAndroid.so:system/lib/egl/eglsubAndroid.so \
    vendor/lge/vs920/proprietary/etc/rpm.mbn:system/etc/rpm.mbn \
    vendor/lge/vs920/proprietary/etc/sbl1.mbn:system/etc/sbl1.mbn \
    vendor/lge/vs920/proprietary/etc/sbl2.mbn:system/etc/sbl2.mbn \
    vendor/lge/vs920/proprietary/etc/sbl3.mbn:system/etc/sbl3.mbn \
    vendor/lge/vs920/proprietary/etc/tz.mbn:system/etc/tz.mbn \
    vendor/lge/vs920/proprietary/etc/firmware/dsps_fluid.b00:system/etc/firmware/dsps_fluid.b00 \
    vendor/lge/vs920/proprietary/etc/firmware/dsps_fluid.b01:system/etc/firmware/dsps_fluid.b01 \
    vendor/lge/vs920/proprietary/etc/firmware/dsps_fluid.b02:system/etc/firmware/dsps_fluid.b02 \
    vendor/lge/vs920/proprietary/etc/firmware/dsps_fluid.b03:system/etc/firmware/dsps_fluid.b03 \
    vendor/lge/vs920/proprietary/etc/firmware/dsps_fluid.mdt:system/etc/firmware/dsps_fluid.mdt \
    vendor/lge/vs920/proprietary/etc/firmware/fw_bcmdhd.bin:system/etc/firmware/fw_bcmdhd.bin \
    vendor/lge/vs920/proprietary/etc/firmware/fw_bcmdhd_apsta.bin:system/etc/firmware/fw_bcmdhd_apsta.bin \
    vendor/lge/vs920/proprietary/etc/firmware/fw_bcmdhd_mfgtest.bin:system/etc/firmware/fw_bcmdhd_mfgtest.bin \
    vendor/lge/vs920/proprietary/etc/firmware/fw_bcmdhd_p2p.bin:system/etc/firmware/fw_bcmdhd_p2p.bin \
    vendor/lge/vs920/proprietary/etc/firmware/yamato_pfp.fw:system/etc/firmware/yamato_pfp.fw \
    vendor/lge/vs920/proprietary/etc/firmware/yamato_pm4.fw:system/etc/firmware/yamato_pm4.fw \
    vendor/lge/vs920/proprietary/etc/firmware/leia_pfp_470.fw:system/etc/firmware/leia_pfp_470.fw \
    vendor/lge/vs920/proprietary/etc/firmware/leia_pm4_470.fw:system/etc/firmware/leia_pm4_470.fw \
    vendor/lge/vs920/proprietary/bin/BCM4330B14.hcd:system/bin/BCM4330B14.hcd \
    vendor/lge/vs920/proprietary/lib/libC2D2.so:system/lib/libC2D2.so \
    vendor/lge/vs920/proprietary/lib/libOpenVG.so:system/lib/libOpenVG.so \
    vendor/lge/vs920/proprietary/lib/libgsl.so:system/lib/libgsl.so \
    vendor/lge/vs920/proprietary/lib/libsc-a2xx.so:system/lib/libsc-a2xx.so \
    vendor/lge/vs920/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/lge/vs920/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/lge/vs920/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/lge/vs920/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/lge/vs920/proprietary/bin/rild:system/bin/rild \
    vendor/lge/vs920/proprietary/bin/qcks:system/bin/qcks \
    vendor/lge/vs920/proprietary/bin/ks:system/bin/ks \
    vendor/lge/vs920/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/lge/vs920/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/lge/vs920/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/lge/vs920/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/vs920/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/lge/vs920/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/lge/vs920/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/lge/vs920/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/lge/vs920/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/lge/vs920/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/lge/vs920/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/lge/vs920/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/lge/vs920/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/lge/vs920/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/lge/vs920/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/lge/vs920/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
    vendor/lge/vs920/proprietary/lib/libnv.so:system/lib/libnv.so \
    vendor/lge/vs920/proprietary/lib/libdsm.so:system/lib/libdsm.so \
    vendor/lge/vs920/proprietary/lib/libqueue.so:system/lib/libqueue.so \
    vendor/lge/vs920/proprietary/lib/libtime_remote_atom.so:system/lib/libtime_remote_atom.so \
    vendor/lge/vs920/proprietary/bin/thermald:system/bin/thermald \
    vendor/lge/vs920/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/lge/vs920/proprietary/lib/libthermal_mitigation_fusion.so:system/lib/libthermal_mitigation_fusion.so \
    vendor/lge/vs920/proprietary/lib/libthermal_mitigation.so:system/lib/libthermal_mitigation.so \
    vendor/lge/vs920/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/lge/vs920/proprietary/lib/libaudio_init.so:system/lib/libaudio_init.so \
    vendor/lge/vs920/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/lge/vs920/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
    vendor/lge/vs920/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/lge/vs920/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
    vendor/lge/vs920/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/lge/vs920/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/lge/vs920/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/lge/vs920/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/lge/vs920/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
    vendor/lge/vs920/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
    vendor/lge/vs920/proprietary/lib/lib_LG_fastaf_v2.0.so:system/lib/lib_LG_fastaf_v2.0.so \
    vendor/lge/vs920/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/lge/vs920/proprietary/lib/libchromatix_imx105_preview.so:system/lib/libchromatix_imx105_preview.so \
    vendor/lge/vs920/proprietary/lib/hw/audio.primary.msm8660.so:system/lib/hw/audio.primary.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/audio_policy.msm8660.so:system/lib/hw/audio_policy.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/copybit.msm8660.so:system/lib/hw/copybit.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/gralloc.msm8660.so:system/lib/hw/gralloc.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/hwcomposer.msm8660.so:system/lib/hw/hwcomposer.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/sensors.msm8660.so:system/lib/hw/sensors.msm8660.so \
    vendor/lge/vs920/proprietary/lib/hw/camera.msm8660.so:system/lib/hw/camera.msm8660.so \
    vendor/lge/vs920/proprietary/bin/ami304d:system/bin/ami304d \
    vendor/lge/vs920/proprietary/lib/libv8.so:system/lib/libv8.so \
    vendor/lge/vs920/proprietary/lib/modules/ansi_cprng.ko:system/lib/modules/ansi_cprng.ko \
    vendor/lge/vs920/proprietary/lib/modules/bthid.ko:system/lib/modules/bthid.ko \
    vendor/lge/vs920/proprietary/lib/modules/cls_flow.ko:system/lib/modules/cls_flow.ko \
    vendor/lge/vs920/proprietary/lib/modules/cpaccess.ko:system/lib/modules/cpaccess.ko \
    vendor/lge/vs920/proprietary/lib/modules/dal_remotetest.ko:system/lib/modules/dal_remotetest.ko \
    vendor/lge/vs920/proprietary/lib/modules/dma_test.ko:system/lib/modules/dma_test.ko \
    vendor/lge/vs920/proprietary/lib/modules/evbug.ko:system/lib/modules/evbug.ko \
    vendor/lge/vs920/proprietary/lib/modules/gspca_main.ko:system/lib/modules/gspca_main.ko \
    vendor/lge/vs920/proprietary/lib/modules/ksapi.ko:system/lib/modules/ksapi.ko \
    vendor/lge/vs920/proprietary/lib/modules/lcd.ko:system/lib/modules/lcd.ko \
    vendor/lge/vs920/proprietary/lib/modules/max2165.ko:system/lib/modules/max2165.ko \
    vendor/lge/vs920/proprietary/lib/modules/mc44s803.ko:system/lib/modules/mc44s803.ko \
    vendor/lge/vs920/proprietary/lib/modules/msm-buspm-dev.ko:system/lib/modules/msm-buspm-dev.ko \
    vendor/lge/vs920/proprietary/lib/modules/msm_tsif.ko:system/lib/modules/msm_tsif.ko \
    vendor/lge/vs920/proprietary/lib/modules/mt2060.ko:system/lib/modules/mt2060.ko \
    vendor/lge/vs920/proprietary/lib/modules/mt20xx.ko:system/lib/modules/mt20xx.ko \
    vendor/lge/vs920/proprietary/lib/modules/mt2131.ko:system/lib/modules/mt2131.ko \
    vendor/lge/vs920/proprietary/lib/modules/mt2266.ko:system/lib/modules/mt2266.ko \
    vendor/lge/vs920/proprietary/lib/modules/mxl5005s.ko:system/lib/modules/mxl5005s.ko \
    vendor/lge/vs920/proprietary/lib/modules/mxl5007t.ko:system/lib/modules/mxl5007t.ko \
    vendor/lge/vs920/proprietary/lib/modules/oprofile.ko:system/lib/modules/oprofile.ko \
    vendor/lge/vs920/proprietary/lib/modules/qt1010.ko:system/lib/modules/qt1010.ko \
    vendor/lge/vs920/proprietary/lib/modules/sch_dsmark.ko:system/lib/modules/sch_dsmark.ko \
    vendor/lge/vs920/proprietary/lib/modules/scsi_wait_scan.ko:system/lib/modules/scsi_wait_scan.ko \
    vendor/lge/vs920/proprietary/lib/modules/spidev.ko:system/lib/modules/spidev.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda18212.ko:system/lib/modules/tda18212.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda18218.ko:system/lib/modules/tda18218.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda18271.ko:system/lib/modules/tda18271.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda827x.ko:system/lib/modules/tda827x.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda8290.ko:system/lib/modules/tda8290.ko \
    vendor/lge/vs920/proprietary/lib/modules/tda9887.ko:system/lib/modules/tda9887.ko \
    vendor/lge/vs920/proprietary/lib/modules/tea5761.ko:system/lib/modules/tea5761.ko \
    vendor/lge/vs920/proprietary/lib/modules/tea5767.ko:system/lib/modules/tea5767.ko \
    vendor/lge/vs920/proprietary/lib/modules/tsif_chrdev.ko:system/lib/modules/tsif_chrdev.ko \
    vendor/lge/vs920/proprietary/lib/modules/tuner-simple.ko:system/lib/modules/tuner-simple.ko \
    vendor/lge/vs920/proprietary/lib/modules/tuner-types.ko:system/lib/modules/tuner-types.ko \
    vendor/lge/vs920/proprietary/lib/modules/tuner-xc2028.ko:system/lib/modules/tuner-xc2028.ko \
    vendor/lge/vs920/proprietary/lib/modules/vpnclient.ko:system/lib/modules/vpnclient.ko \
    vendor/lge/vs920/proprietary/lib/modules/xc5000.ko:system/lib/modules/xc5000.ko
